app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
  return redirect('pin');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
  Route::auth();
  Route::resource('pin', 'PinController');
  Route::get('pin/{pin}/like', [
    'as' => 'pin.like',
    'uses' => 'PinController@like',
  ]);
});

app/Pin.php
<?php

namespace App;

use \Conner\Likeable\LikeableTrait;
use Illuminate\Database\Eloquent\Model;

class Pin extends Model
{
  use LikeableTrait;

  /**
   * Get the user for this pin
   */
  public function user () {
    return $this->belongsTo('App\User');
  }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    'name', 'email', 'password',
  ];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = [
    'password', 'remember_token',
  ];

  /**
   * Get pins for the user
   */
  public function pins () {
    return $this->hasMany('App\Pin');
  }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PinController.php
<?php

namespace App\Http\Controllers;

use File;
use Image;
use Gate;
use App\User;
use App\Pin;
use Illuminate\Http\Request;

use App\Http\Requests;

class PinController extends Controller
{
  /**
   * Holds the validation array for storing and updating
   *
   * @var array $rules
   */
  private $storingRules = [
    'title' => 'required|min:6',
    'description' => 'required|min:6',
    'image' => 'required|mimes:png,jpg,jpeg'
  ];

  private $updatingRules = [
    'title' => 'required|min:6',
    'description' => 'required|min:6',
    'image' => 'mimes:png,jpg,jpeg'
  ];


  /**
   * Constructs the controller
   */
  public function __construct () {
    $this->middleware('auth', ['except' => [
      'index',
      'show',
    ]]);
  }

  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $pins = Pin::orderBy('created_at', 'desc')->get();

    return view('pin.index', [
      'pins' => $pins,
    ]);
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    return view('pin.create');
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $this->validate($request, $this->storingRules);

    $imageName = $this->storeImage($request->file('image'));

    $pin = new Pin;
    $pin->title = $request->title;
    $pin->description = $request->description;
    $pin->user_id = $request->user()->id;
    $pin->image = $imageName;
    $pin->save();

    return redirect('pin/' . $pin->id)
            ->with('notice', 'Successfully created new Pin');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show($id)
  {
    $pin = Pin::find($id);

    return view('pin.show', [
      'pin' => $pin,
    ]);
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit($id)
  {
    $pin = Pin::find($id);

    if (Gate::denies('modify', $pin)) {
      abort(403);
    }

    return view('pin.edit', [
      'pin' => $pin,
    ]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, $id)
  {
    $pin = Pin::find($id);

    if (Gate::denies('modify', $pin)) {
      abort(403);
    }

    $this->validate($request, $this->updatingRules);

    if ($request->hasFile('image')) {
      $imageName = $this->storeImage($request->file('image'));

      File::delete(public_path('assets/img/pins/') . $pin->image);

      $pin->image = $imageName;
    }

    $pin->title = $request->title;
    $pin->description = $request->description;
    $pin->save();

    return redirect('pin/' . $pin->id)
            ->with('notice', 'Successfully edited Pin');
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy($id)
  {
    $pin = Pin::find($id);

    if (Gate::denies('modify', $pin)) {
      abort(403);
    }

    File::delete(public_path('assets/img/pins/') . $pin->image);
    $pin->delete();

    return redirect('/');
  }

  /**
   * Like the specified pin
   *
   * @param int $id
   * @return \Illuminate\Http\Response
   */
  public function like($id) {
    $pin = Pin::find($id);

    if (!$pin->liked()) $pin->like();
    else $pin->unlike();

    return redirect('pin/' . $pin->id);
  }

  /**
   * Stores the image to filesystem
   *
   * @param $request->file() $image
   * @return String
   */
  private function storeImage ($image) {
    $imageName = md5($image->getClientOriginalName() . microtime())
                  . '.' . $image->getClientOriginalExtension();

    Image::make($image)
            ->resize(800, null, function ($constraint) {
              $constraint->aspectRatio();
            })
            ->save(public_path('assets/img/pins/') . $imageName);

    return $imageName;
  }

}

resources/views/common/error.blade.php
@if(count($errors) > 0)

  <div id="errors">
    <h2>{{ count($errors) }} {{ str_plural('error', count($errors)) }} prevented this Pin from saving</h2>
    
    <ul>
      @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>

@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Pin Board</title>

  <!-- Fonts -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>

  <!-- Styles -->
  <link href="{{ URL::asset('includes/bootstrap-3.3.6/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ URL::asset('assets/css/main.css') }}" rel="stylesheet">
  {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

  <style>
    body {
      font-family: 'Lato';
    }

    .fa-btn {
      margin-right: 6px;
    }
  </style>
</head>
<body id="app-layout">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <!-- Collapsed Hamburger -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <!-- Branding Image -->
        <a class="navbar-brand" href="{{ url('/') }}">
          Pin Board
        </a>
      </div>

      <div class="collapse navbar-collapse" id="app-navbar-collapse">
        <!-- Right Side Of Navbar -->
        <ul class="nav navbar-nav navbar-right">
          <!-- Authentication Links -->
          @if (Auth::guest())
            <li><a href="{{ url('/login') }}">Login</a></li>
            <li><a href="{{ url('/register') }}">Register</a></li>
          @else
            <li><a href="{{ route('pin.create') }}">New Pin</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                {{ Auth::user()->name }} <span class="caret"></span>
              </a>

              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Account</a></li>
                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
              </ul>
            </li>
          @endif
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        @if (session('notice'))
          <div class="alert alert-info">{{ session('notice') }}</div>
        @endif
      </div>
    </div>

    @yield('content')
  </div>

  <!-- JavaScripts -->
  <script src="{{ URL::asset('includes/jquery/jquery-2.2.1.min.js') }}"></script>
  <script src="{{ URL::asset('includes/bootstrap-3.3.6/js/bootstrap.min.js') }}"></script>
  <script src="{{ URL::asset('includes/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
  <script src="{{ URL::asset('includes/masonry/masonry.pkgd.min.js') }}"></script>
  <script src="{{ URL::asset('assets/js/app.js') }}"></script>
</body>
</html>

resources/views/pin/create.blade.php
@extends('layouts.app')

@section('content')

  <div class="col-md-6 col-md-offset-3">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Pin</h1>
      </div>
      <div class="panel-body">
        @include('common.error')

        <form action="{{ url('pin') }}"
              method="POST"
              enctype="multipart/form-data">

          {{ csrf_field() }}

          <div class="form-group">
            <label for="title">Title</label>
            <input name="title"
                    id="title"
                    type="text"
                    class="form-control"
                    value="{{ old('title') }}">
          </div>

          <div class="form-group">
            <label for="description">Description</label>
            <textarea name="description"
                    id="description"
                    type="text"
                    class="form-control">
                    {{ old('description') }}
            </textarea>
          </div>

          <div class="form-group">
            <label for="image">Image</label>
            <input type="file"
                    name="image"
                    id="image"
                    accept="image/*"
                    class="form-control">
          </div>

          <button type="submit" class="btn btn-primary">Create Pin</button>

        </form>
      </div>
    </div>

    <a href="{{ url('/') }}">Back</a>
  </div>

@endsection

resources/views/pin/edit.blade.php
@extends('layouts.app')

@section('content')

  <div id="edit_page">

    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h1>Edit Pin</h1>
        </div>
        <div class="panel-body">

          @include('common.error')

          <strong class="center">Current Image</strong>
          <img src="{{ URL::asset('assets/img/pins/' . $pin->image) }}"
                alt="{{ $pin->title }}"
                class="current_image">

          <form action="{{ route('pin.update', ['pin' => $pin->id]) }}"
                method="POST"
                enctype="multipart/form-data">

            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group">
              <label for="title">Title</label>
              <input name="title"
                      id="title"
                      type="text"
                      class="form-control"
                      value="{{ $pin->title }}">
            </div>

            <div class="form-group">
              <label for="description">Description</label>
              <textarea name="description"
                      id="description"
                      type="text"
                      class="form-control">
                      {{ $pin->description }}
              </textarea>
            </div>

            <div class="form-group">
              <label for="image">Image</label>
              <input type="file"
                      name="image"
                      id="image"
                      accept="image/*"
                      class="form-control">
            </div>

            <button type="submit" class="btn btn-primary">Save Pin</button>

          </form>

        </div>
      </div>

      <a href="{{ url('pin/' . $pin->id) }}">Cancel</a>
    </div>

  </div>

@endsection

resources/views/pin/index.blade.php
@extends('layouts.app')

@section('content')

  <div id="pins" class="transition-enabled">
    @foreach ($pins as $pin)
      <div class="box panel panel-default">

        <a href="{{ url('pin/' . $pin->id) }}">
          <img src="{{ URL::asset('assets/img/pins/' . $pin->image) }}" alt="{{ $pin->title }}">
        </a>

        <div class="panel-body">
          <h2>
            <a href="{{ url('pin/' . $pin->id) }}">{{ $pin->title }}</a>
          </h2>
          <p class="user">By {{ $pin->user->name }}</p>
        </div>

      </div>
    @endforeach
  </div>

@endsection

resources/views/pin/show.blade.php
@extends('layouts.app')

@section('content')

  <div id="pin_show" class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading pin_image">
          <img src="{{ URL::asset('assets/img/pins/' . $pin->image) }}" alt="{{ $pin->title }}">
        </div>
        <div class="panel-body">
          <h1>{{ $pin->title }}</h1>
          <p class="description">{{ $pin->description }}</p>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-sm-6">
              <p class="user">Submitted by {{ $pin->user->name }}</p>
            </div>
            <div class="col-sm-6">
              <div class="btn-group pull-right">
                <a href="{{ route('pin.like', ['pin' => $pin->id]) }}" class="btn btn-default">
                  @if (Auth::guest())
                    <i class="fa fa-heart-o"></i>
                  @else
                    @if ($pin->liked())
                      <i class="fa fa-heart"></i>
                    @else
                      <i class="fa fa-heart-o"></i>
                    @endif
                  @endif
                  &nbsp;&nbsp;{{ $pin->likeCount }}
                </a>
                @can ('modify', $pin)
                  <a href="{{ route('pin.edit', ['pin' => $pin->id]) }}" class="btn btn-default">Edit</a>
                  <form action="{{ route('pin.destroy', ['pin' => $pin->id]) }}"
                        method="POST"
                        class="btn btn-danger link">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit">Delete</button>
                  </form>
                @endcan
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

@endsection